### PR TITLE
Fix/float conversion error

### PR DESCRIPTION
**Pull request by JagjitBhatia**
Issue #12  [Error] could not convert string to float: 'N/'

Explanation: Your code currently checks to see if 'N/A' is in the decoded line but, sometimes, FFMPEG doesn't output the full 'N/A'. Requesting to change to a try/except block to handle any case where the speed can't be converted into a float.

### CODE REVIEW

**Comment by CrypticSignal** [comment]
Thanks for opening a PR. I'd like to request a couple of changes.

- Instead of creating an if-statement [here](https://github.com/CrypticSignal/better-ffmpeg-progress/pull/11/files#diff-6a67f7de23295b2fbf8da12ce82dcd6fa297484cd88dfeb86bdbb851d33c72f0R90), you can add this condition to the line above, i.e. `elif "out_time_ms" in ffmpeg_output and 'N/A' not in ffmpeg_output.strip()[12:]`

- Replace `speed = None` in the `except` block with `continue`.

**Comment by CrypticSignal** [comment]
According to #12, FFmpeg sometimes outputs `N/`, so the check should be `N/ not in ...` instead.

Closing this as I haven't heard back from the author of this PR for over a month. If you're going to contribute, and this goes to whoever reads this, please respond in a reasonable timeframe.

**Comment by F-park** [comment]
https://github.com/CrypticSignal/better-ffmpeg-progress/blob/54be3c4ff611676ecddd812e35eb3555f838a07c/better_ffmpeg_progress/better_ffmpeg_progress.py#L101-L105

#### The `TypeError` caused by this code. 
- value will be `22.3x` or `N/A`, and speed_str will be `22.3` or `N/` (line 102)
- so `bool(speed_str != "0" and "N/A" not in speed_str) == True` (line 104)
- `float("N/")` will `raise TypeError()` (line 105)
 
BTW, it will fix in #17

**Comment by F-park** [comment]
> > speed_str will be 22.3 or N/
> 
> @F-park If this is the case, `"N/A" not in` in the if statement needs to be changed to `"N/" not in`

it will cause some bug in other case, we should change it to this.

```py
elif "speed" in ffmpeg_output:
    speed_str = value.rstrip("x")  # rstrip `22.3x` to `22.3`, and preserve `N/A`

        if speed_str != "0" and "N/A" not in speed_str:
            self._speed = float(speed_str)
```

**Pull request closed without merging**
